apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-e-commerce-product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name:  product-db
        image: mongo:latest