apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-e-commerce-cart-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-db
  template:
    metadata:
      labels:
        app: cart-db
    spec:
      containers:
      - name:  cart-db
        image: mongo:latest