apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-e-commerce-auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: safeerep/auth-orchestration-experiment
        name: auth
        envFrom:
        - configMapRef:
            name: auth-config
