apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-e-commerce-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name:  auth-db
        image: mongo:latest