apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-e-commerce-order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name:  order-db
        image: mongo:latest