apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  PORT: "4003"
  MONGO_URI: "mongodb://mini-e-commerce-order-db:27017/orchestrationExpOrder"
  SALT_ROUNDS: "10"
  SESSION_SECRET: "writtenBySafeer"
  JWT_TOKEN_SECRET: "9f895f69b264aff29593af6a1076401c3005cc269"